name: My First Worflow
on:
  push:
    branches:
      - main
#test 1
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run eslint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm test